/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ApiKeyUpdateManyWithoutApplicationsInput } from "./ApiKeyUpdateManyWithoutApplicationsInput";
import { ValidateNested, IsOptional, IsEnum, IsString } from "class-validator";
import { Type } from "class-transformer";
import { EnumApplicationCategories } from "./EnumApplicationCategories";
import { CredentialUpdateManyWithoutApplicationsInput } from "./CredentialUpdateManyWithoutApplicationsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { WebhookUpdateManyWithoutApplicationsInput } from "./WebhookUpdateManyWithoutApplicationsInput";

@InputType()
class ApplicationUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ApiKeyUpdateManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => ApiKeyUpdateManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => ApiKeyUpdateManyWithoutApplicationsInput, {
    nullable: true,
  })
  apiKey?: ApiKeyUpdateManyWithoutApplicationsInput;

  @ApiProperty({
    required: false,
    enum: EnumApplicationCategories,
    isArray: true,
  })
  @IsEnum(EnumApplicationCategories, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumApplicationCategories], {
    nullable: true,
  })
  categories?: Array<
    "calendar" | "messaging" | "other" | "payment" | "video" | "web3"
  >;

  @ApiProperty({
    required: false,
    type: () => CredentialUpdateManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => CredentialUpdateManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => CredentialUpdateManyWithoutApplicationsInput, {
    nullable: true,
  })
  credentials?: CredentialUpdateManyWithoutApplicationsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  dirName?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  keys?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => WebhookUpdateManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => WebhookUpdateManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => WebhookUpdateManyWithoutApplicationsInput, {
    nullable: true,
  })
  webhook?: WebhookUpdateManyWithoutApplicationsInput;
}

export { ApplicationUpdateInput as ApplicationUpdateInput };
