/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ApiKeyCreateNestedManyWithoutApplicationsInput } from "./ApiKeyCreateNestedManyWithoutApplicationsInput";
import { ValidateNested, IsOptional, IsEnum, IsString } from "class-validator";
import { Type } from "class-transformer";
import { EnumApplicationCategories } from "./EnumApplicationCategories";
import { CredentialCreateNestedManyWithoutApplicationsInput } from "./CredentialCreateNestedManyWithoutApplicationsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { WebhookCreateNestedManyWithoutApplicationsInput } from "./WebhookCreateNestedManyWithoutApplicationsInput";

@InputType()
class ApplicationCreateInput {
  @ApiProperty({
    required: false,
    type: () => ApiKeyCreateNestedManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => ApiKeyCreateNestedManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => ApiKeyCreateNestedManyWithoutApplicationsInput, {
    nullable: true,
  })
  apiKey?: ApiKeyCreateNestedManyWithoutApplicationsInput;

  @ApiProperty({
    required: true,
    enum: EnumApplicationCategories,
    isArray: true,
  })
  @IsEnum(EnumApplicationCategories, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumApplicationCategories], {
    nullable: true,
  })
  categories?: Array<
    "calendar" | "messaging" | "other" | "payment" | "video" | "web3"
  >;

  @ApiProperty({
    required: false,
    type: () => CredentialCreateNestedManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => CredentialCreateNestedManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => CredentialCreateNestedManyWithoutApplicationsInput, {
    nullable: true,
  })
  credentials?: CredentialCreateNestedManyWithoutApplicationsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  dirName!: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  keys?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => WebhookCreateNestedManyWithoutApplicationsInput,
  })
  @ValidateNested()
  @Type(() => WebhookCreateNestedManyWithoutApplicationsInput)
  @IsOptional()
  @Field(() => WebhookCreateNestedManyWithoutApplicationsInput, {
    nullable: true,
  })
  webhook?: WebhookCreateNestedManyWithoutApplicationsInput;
}

export { ApplicationCreateInput as ApplicationCreateInput };
